threebrs_admin_sorting_index:
    path: /sorting
    defaults:
        _controller: ThreeBRS\SortingPlugin\Controller\SortingController::index

threebrs_admin_sorting_products_save:
    path: /sorting/save
    defaults:
        _controller: ThreeBRS\SortingPlugin\Controller\SortingController::savePositions

threebrs_admin_sorting_products:
    path: /sorting/taxon/{taxonId}
    defaults:
        _controller: ThreeBRS\SortingPlugin\Controller\SortingController::products

